<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://ros.org/wiki/xacro" >

    <xacro:property name="base_length" value="0.5" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.14" />
    <xacro:property name="wheel_radius" value="0.04" />
    <xacro:property name="wheel_length" value="0.03" />
    <xacro:property name="caster_wheel_radius" value="0.005" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="0.5" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${2*caster_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${2*caster_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="${2*caster_wheel_radius}"
                              xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="caster_wheel_link1">
        <visual>
            <geometry>
                <sphere radius="${2*caster_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${2*caster_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="${2*caster_wheel_radius}"
                              xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${0.023 + base_height/2.0}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="0 ${-(base_width - wheel_length) / 2.0} -0.05" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="0 ${(base_width - wheel_length) / 2.0} -0.05" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="0.1611 0 ${-(base_height/ 2.0 + 0.009)}" rpy="0 0 0" />
    </joint>

    <joint name="base_caster_wheel_joint1" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link1" />
        <origin xyz="-0.1611 0 ${-(base_height/ 2.0 + 0.009)}" rpy="0 0 0" />
    </joint>

    <link name="imu_link">
        <inertial>
            <origin xyz="-0.00552433659106688 0.000168210391520346 0.000514000497342681" rpy="0 0 0" />
                <mass value="0.000528415362211671" />
                <inertia 
                ixx="1.46176048428261E-08" ixy="1.40015117949421E-10" ixz="-1.99633872937403E-12"
                iyy="8.59662482954888E-09" iyz="7.52375112767959E-12"
                izz="2.30279421279312E-08" />
        </inertial>

        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>

        <collision>
            <geometry>
                <box size="0.05 0.05 0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
    </link>

    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 0.08" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="imu_link" />
        <axis xyz="0 0 0" />
    </joint>
    <link name="laser_link">
        <inertial>
            <origin xyz="-0.011945780406062 -0.000381929217680526 -0.0170649378129477" rpy="0 0 0" />
                <mass value="0.073084435549317" />
                <inertia 
                ixx="1.96074931730795E-05" ixy="-3.62091076640009E-07" ixz="4.28230084046735E-07" 
                iyy="2.40983835136327E-05" iyz="1.50180909250652E-08" 
                izz="4.14184164228595E-05" />
        </inertial>

        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>

        <collision>
            <geometry>
                <box size="0.1 0.1 0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

    </link>

    <joint name="laser_joint" type="fixed">
        <origin xyz="0 0 0.08" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="laser_link" />
    </joint>

</robot>